set_property PACKAGE_PIN M15 [get_ports in_1[0]]
set_property PACKAGE_PIN H17 [get_ports in_1[1]]
set_property PACKAGE_PIN H18 [get_ports in_2[0]]
set_property PACKAGE_PIN H19 [get_ports in_2[1]]
set_property PACKAGE_PIN F22 [get_ports s_1]
set_property PACKAGE_PIN U14 [get_ports out_1[0]]
set_property PACKAGE_PIN U19 [get_ports out_1[1]]

set_property IOSTANDARD LVCMOS18 [get_ports in_1[0]]
set_property IOSTANDARD LVCMOS18 [get_ports in_1[1]]
set_property IOSTANDARD LVCMOS18 [get_ports in_2[0]]
set_property IOSTANDARD LVCMOS18 [get_ports in_2[1]]
set_property IOSTANDARD LVCMOS18 [get_ports s_1]
set_property IOSTANDARD LVCMOS33 [get_ports out_1[0]]
set_property IOSTANDARD LVCMOS33 [get_ports out_1[1]]
