set_property PACKAGE_PIN M15 [get_ports IN_1[0]]
set_property PACKAGE_PIN H17 [get_ports IN_1[1]]
set_property PACKAGE_PIN H18 [get_ports IN_2[0]]
set_property PACKAGE_PIN H19 [get_ports IN_2[1]]
set_property PACKAGE_PIN F22 [get_ports S]
set_property PACKAGE_PIN U14 [get_ports O]

set_property IOSTANDARD LVCMOS18 [get_ports IN_1[0]]
set_property IOSTANDARD LVCMOS18 [get_ports IN_1[1]]
set_property IOSTANDARD LVCMOS18 [get_ports IN_2[0]]
set_property IOSTANDARD LVCMOS18 [get_ports IN_2[1]]
set_property IOSTANDARD LVCMOS18 [get_ports S]
set_property IOSTANDARD LVCMOS33 [get_ports O]