set_property PACKAGE_PIN M15 [get_ports op1[0]]
set_property PACKAGE_PIN H17 [get_ports op1[1]]
set_property PACKAGE_PIN H18 [get_ports op2[0]]
set_property PACKAGE_PIN H19 [get_ports op2[1]]
set_property PACKAGE_PIN U14 [get_ports out[0]]
set_property PACKAGE_PIN U19 [get_ports out[1]]
set_property PACKAGE_PIN W22 [get_ports out[2]]
set_property PACKAGE_PIN V22 [get_ports out[3]]

set_property IOSTANDARD LVCMOS18 [get_ports op1[0]]
set_property IOSTANDARD LVCMOS18 [get_ports op1[1]]
set_property IOSTANDARD LVCMOS18 [get_ports op2[0]]
set_property IOSTANDARD LVCMOS18 [get_ports op2[1]]
set_property IOSTANDARD LVCMOS33 [get_ports out[0]]
set_property IOSTANDARD LVCMOS33 [get_ports out[1]]
set_property IOSTANDARD LVCMOS33 [get_ports out[2]]
set_property IOSTANDARD LVCMOS33 [get_ports out[3]]